export type ParameterEntry = {
  key: string;
  name: string;
  symbol: string;
  unit: string;
  evidence: "Process input" | "Literature-shaped" | "Exploratory";
  intuition: string;
  increase: string;
  watch: string;
  model: string;
};

export type ParameterGroup = {
  id: string;
  number: string;
  title: string;
  description: string;
  parameters: ParameterEntry[];
};

export const parameterGroups: ParameterGroup[] = [
  {
    id: "path",
    number: "02",
    title: "Path and slicing",
    description: "These controls decide where the focus travels, how neighboring lines overlap, and when a region is revisited.",
    parameters: [
      {
        key: "layer-height",
        name: "Layer height",
        symbol: "Δz",
        unit: "µm",
        evidence: "Process input",
        intuition: "The vertical distance between successive written slices.",
        increase: "Uses fewer, more widely separated layers. Exposure is faster, but vertical detail and overlap decrease.",
        watch: "Numerical aperture, wavelength, hatch spacing, and the smallest vertical feature.",
        model: "Rebuilds the deterministic three-dimensional path and therefore changes layer count, path length, timing, and exposure overlap.",
      },
      {
        key: "hatch-spacing",
        name: "Hatch spacing",
        symbol: "h",
        unit: "µm",
        evidence: "Process input",
        intuition: "The lateral distance between neighboring interior scan lines.",
        increase: "Shortens the path and reduces overlap. Excessive spacing can leave weakly exposed gaps between lines.",
        watch: "Focal width, power, speed, layer height, and contour coverage.",
        model: "Changes the actual path samples through the occupancy rather than applying a cosmetic density multiplier.",
      },
      {
        key: "hatch-angle",
        name: "Hatch angle",
        symbol: "θ",
        unit: "°",
        evidence: "Process input",
        intuition: "The in-plane direction followed by the interior fill lines.",
        increase: "Rotates the hatch; it has no universal stronger-or-weaker direction. Its effect depends on geometry and neighboring layers.",
        watch: "Feature orientation, boundary coverage, layer-to-layer rotation, and unsupported spans.",
        model: "Rotates the generated scan trajectory inside each layer while preserving the occupied target volume.",
      },
      {
        key: "contour-passes",
        name: "Contour passes",
        symbol: "N꜀",
        unit: "count",
        evidence: "Process input",
        intuition: "How many boundary-following traces reinforce the outside of each slice.",
        increase: "Adds exposure near boundaries and lengthens the path. Edges may become more robust but also broader or overexposed.",
        watch: "Hatch spacing, power, speed, off-target activation, and fine cavities.",
        model: "Adds real contour trajectories to the exposure schedule; it is not a post-processing outline.",
      },
      {
        key: "exposure-passes",
        name: "Exposure passes",
        symbol: "Nₚ",
        unit: "count",
        evidence: "Process input",
        intuition: "How many times the complete path is revisited.",
        increase: "Accumulates more exposure, but later passes encounter chemistry altered by earlier passes.",
        watch: "Initiator depletion, oxygen recovery, radical loss, power, and total physical time.",
        model: "Repeats the timed path against the evolving authoritative volume instead of multiplying a finished conversion field.",
      },
    ],
  },
  {
    id: "light",
    number: "03",
    title: "Light and motion",
    description: "These are physical-style process inputs that shape the focal field, pulse energy, nonlinear source, and dwell history.",
    parameters: [
      {
        key: "power",
        name: "Specimen power",
        symbol: "P",
        unit: "mW",
        evidence: "Process input",
        intuition: "The average optical power delivered at the specimen plane.",
        increase: "Strengthens the two-photon source rapidly. In this model the source scales with P² when other light inputs stay fixed.",
        watch: "Scan speed, repetition rate, pulse duration, numerical aperture, and off-target activation.",
        model: "Power normalizes the vectorial pupil and enters the nonlinear source; it is not divided uniformly among voxels.",
      },
      {
        key: "speed",
        name: "Scan speed",
        symbol: "v",
        unit: "µm/s",
        evidence: "Process input",
        intuition: "How quickly the focus moves along the same geometric path.",
        increase: "Reduces dwell time and usually lowers accumulated conversion while shortening the physical exposure history.",
        watch: "Power, hatch spacing, passes, diffusion, oxygen recovery, and radical lifetime.",
        model: "Changes illuminated and dark time between path samples. It does not directly rescale the optical field.",
      },
      {
        key: "na",
        name: "Numerical aperture",
        symbol: "NA",
        unit: "dimensionless",
        evidence: "Process input",
        intuition: "How broadly the objective accepts light and how tightly it can concentrate the same total specimen power.",
        increase: "Narrows the focal distribution and raises central concentration, but can reduce overlap and does not guarantee greater whole-object survival.",
        watch: "Wavelength, voxel pitch, hatch and layer spacing, polarization, and aberration.",
        model: "Sets the objective semi-angle in a normalized vectorial Debye field. The narrow core is volume-averaged when the grid under-resolves it.",
      },
      {
        key: "wavelength",
        name: "Wavelength",
        symbol: "λ",
        unit: "nm",
        evidence: "Process input",
        intuition: "The optical wavelength used to form the focus.",
        increase: "Broadens diffraction-controlled spatial scales for the same NA. A real material’s absorption response may also change.",
        watch: "NA, photoinitiator spectrum, objective transmission, aberration, and voxel resolution.",
        model: "Changes focal-field geometry. It does not currently look up a wavelength-dependent two-photon cross-section.",
      },
      {
        key: "pulse-duration",
        name: "Pulse duration",
        symbol: "τₚ",
        unit: "fs",
        evidence: "Process input",
        intuition: "How long each ultrafast pulse lasts.",
        increase: "Spreads the same pulse energy over more time, lowering the peak-power proxy and the model’s nonlinear source.",
        watch: "Average power, repetition rate, dispersion, photochemistry, and thermal accumulation.",
        model: "At fixed average power and repetition rate, the source scales approximately with 1/τₚ. Pulse shape and dispersion are not resolved.",
      },
      {
        key: "repetition-rate",
        name: "Repetition rate",
        symbol: "f",
        unit: "MHz",
        evidence: "Process input",
        intuition: "How many pulses arrive each second.",
        increase: "At fixed average power, creates more frequent but less energetic pulses; the current source therefore decreases with 1/f.",
        watch: "Power, pulse duration, radical lifetime, oxygen recovery, and heat accumulation.",
        model: "Sets pulse energy P/f and peak-power proxy. Individual pulses are summarized rather than temporally resolved one by one.",
      },
    ],
  },
  {
    id: "resin",
    number: "04",
    title: "Resin chemistry and transport",
    description: "These coefficients control how excitation becomes radicals, how inhibition competes, and how species move through the volume.",
    parameters: [
      {
        key: "initiator",
        name: "Initial photoinitiator",
        symbol: "p₀",
        unit: "relative",
        evidence: "Exploratory",
        intuition: "The starting reservoir of molecules available to create reactive species.",
        increase: "Provides more initiation capacity and delays exhaustion, subject to oxygen inhibition and depletion.",
        watch: "PI depletion, radical yield, oxygen, source strength, and repeated passes.",
        model: "Initializes the photoinitiator field with a dimensionless relative concentration; it is not a fitted molar concentration.",
      },
      {
        key: "oxygen",
        name: "Boundary oxygen",
        symbol: "o₀",
        unit: "relative",
        evidence: "Exploratory",
        intuition: "The oxygen level available at the volume boundary—a replenishable chemical brake on radicals.",
        increase: "Strengthens inhibition and can delay or suppress conversion, especially in weakly exposed or boundary-adjacent regions.",
        watch: "Oxygen quenching, oxygen diffusion, radical yield, power, and scan timing.",
        model: "Sets the boundary reservoir and initial oxygen field in relative units rather than a calibrated concentration.",
      },
      {
        key: "pi-depletion",
        name: "Photoinitiator depletion",
        symbol: "β",
        unit: "T₀⁻¹",
        evidence: "Literature-shaped",
        intuition: "How quickly exposure consumes the available photoinitiator.",
        increase: "Produces faster depletion, making later exposure less productive even when the optical source is unchanged.",
        watch: "Initial initiator, source strength, pass count, PI diffusion, and radical yield.",
        model: "Appears in the initiator loss term −βsp using the model’s normalized time scale.",
      },
      {
        key: "radical-yield",
        name: "Radical yield",
        symbol: "η",
        unit: "relative",
        evidence: "Exploratory",
        intuition: "How efficiently an absorbed excitation creates active radicals in the compact chemistry model.",
        increase: "Generates more radicals from the same source before quenching, loss, and termination act.",
        watch: "Initiator, oxygen quenching, termination, propagation, and source strength.",
        model: "Multiplies the radical generation term ηsp; it is not a measured quantum yield.",
      },
      {
        key: "dark-loss",
        name: "Dark radical loss",
        symbol: "δ",
        unit: "T₀⁻¹",
        evidence: "Exploratory",
        intuition: "How quickly radicals disappear even when oxygen and radical–radical termination are separated out.",
        increase: "Shortens radical memory between path samples and reduces conversion accumulated during dark intervals.",
        watch: "Scan speed, path jumps, repetition rate, passes, and propagation.",
        model: "Applies a linear radical decay term −δr on the normalized chemical clock.",
      },
      {
        key: "oxygen-quenching",
        name: "Oxygen quenching",
        symbol: "q",
        unit: "relative",
        evidence: "Literature-shaped",
        intuition: "How strongly local oxygen suppresses radical activity.",
        increase: "Makes a given oxygen field more inhibitory and sharpens the competition between exposure and oxygen supply.",
        watch: "Boundary oxygen, oxygen diffusion, radical yield, source strength, and scan dwell.",
        model: "Controls the coupled oxygen–radical sink qor in the compact reaction system.",
      },
      {
        key: "termination",
        name: "Bimolecular termination",
        symbol: "κ",
        unit: "relative",
        evidence: "Exploratory",
        intuition: "The rate at which two active radicals meet and terminate one another.",
        increase: "Suppresses high radical concentrations disproportionately and limits runaway peaks.",
        watch: "Radical yield, diffusion, power, dwell time, and propagation.",
        model: "Applies the nonlinear loss term −κr² with an exploratory dimensionless coefficient.",
      },
      {
        key: "propagation",
        name: "Propagation",
        symbol: "γ",
        unit: "T₀⁻¹",
        evidence: "Exploratory",
        intuition: "How efficiently surviving radicals convert unreacted material into the network-forming state.",
        increase: "Builds conversion faster for the same radical history and approaches saturation sooner.",
        watch: "Radical yield, radical loss, oxygen, gel point, and development resistance.",
        model: "Controls ∂ₜx = γr(1−x); it compresses a larger polymer reaction network into one conversion rate.",
      },
      {
        key: "oxygen-diffusion",
        name: "Oxygen diffusion",
        symbol: "Dₒ",
        unit: "L₀²/T₀",
        evidence: "Literature-shaped",
        intuition: "How quickly oxygen spreads and replenishes depleted regions.",
        increase: "Smooths oxygen gradients and can restore inhibition more quickly behind a moving focus.",
        watch: "Boundary oxygen, quenching, scan timing, feature size, and volume boundaries.",
        model: "Scales the spatial Laplacian of the oxygen field on normalized length and time units.",
      },
      {
        key: "radical-diffusion",
        name: "Radical diffusion",
        symbol: "Dᵣ",
        unit: "L₀²/T₀",
        evidence: "Exploratory",
        intuition: "How quickly radical activity spreads away from where it was generated.",
        increase: "Broadens and smooths radical fields, potentially lowering local peaks while activating nearby regions.",
        watch: "Radical lifetime, termination, hatch spacing, boundaries, and off-target conversion.",
        model: "Diffuses the compact radical field; it does not resolve different radical species or chain lengths.",
      },
      {
        key: "pi-diffusion",
        name: "Photoinitiator diffusion",
        symbol: "Dₚ",
        unit: "L₀²/T₀",
        evidence: "Literature-shaped",
        intuition: "How quickly photoinitiator concentration redistributes after local depletion.",
        increase: "Refills depleted regions more quickly while spreading concentration gradients into neighbors.",
        watch: "PI depletion, pass timing, initial initiator, feature size, and volume boundaries.",
        model: "Diffuses one normalized photoinitiator field without material-specific mobility or binding states.",
      },
    ],
  },
  {
    id: "development",
    number: "05",
    title: "Gelation and development",
    description: "These controls decide when conversion counts as a connected network and how aggressively bath-accessible material is removed.",
    parameters: [
      {
        key: "gel-point",
        name: "Gel point",
        symbol: "xᵍ",
        unit: "conversion",
        evidence: "Exploratory",
        intuition: "The conversion level used to mark material as a connected, gelled network.",
        increase: "Requires more conversion before material counts as gelled, making survival criteria more demanding.",
        watch: "Propagation, exposure history, development resistance, and weak connections.",
        model: "Classifies the continuous conversion field for gel statistics; development also depends continuously on conversion.",
      },
      {
        key: "base-dissolution",
        name: "Base dissolution",
        symbol: "k₀",
        unit: "T₀⁻¹",
        evidence: "Exploratory",
        intuition: "The baseline rate at which accessible, weak material loses mass in developer.",
        increase: "Clears underconverted material faster and makes marginal regions less likely to remain.",
        watch: "Development time, gel resistance, bath depth, conversion, and narrow supports.",
        model: "Sets the base rate in the compact remaining-mass equation; it is not fitted to a specific solvent protocol.",
      },
      {
        key: "gel-resistance",
        name: "Gel resistance",
        symbol: "aₖ",
        unit: "dimensionless",
        evidence: "Exploratory",
        intuition: "How strongly increasing conversion protects material against dissolution.",
        increase: "Makes highly converted regions much more resistant relative to weak regions, sharpening selective development.",
        watch: "Conversion distribution, gel point, base dissolution, and development time.",
        model: "Places conversion in an exponential resistance factor rather than a binary keep-or-delete rule.",
      },
      {
        key: "development-time",
        name: "Development time",
        symbol: "tᵈ",
        unit: "T₀",
        evidence: "Process input",
        intuition: "How long the calculated structure remains exposed to the development process.",
        increase: "Removes more weak material and opens deeper access, but can erode marginally converted features.",
        watch: "Base dissolution, gel resistance, conversion gradients, access paths, and mechanical effects outside the model.",
        model: "Advances bath-accessible dissolution for a normalized duration; rinsing, drying, stress, and capillary collapse remain outside scope.",
      },
    ],
  },
];

export const parameterCount = parameterGroups.reduce(
  (count, group) => count + group.parameters.length,
  0,
);
