/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_reactionlenssimulation_free: (a: number, b: number) => void;
export const reactionlenssimulation_set_parameters: (a: number, b: number, c: number) => void;
export const reactionlenssimulation_set_exposure_steps_total: (a: number, b: number, c: number) => void;
export const reactionlenssimulation_reset: (a: number, b: number) => void;
export const reactionlenssimulation_advance_exposure_steps: (a: number, b: number) => number;
export const reactionlenssimulation_advance_exposure_at_progress_steps: (a: number, b: number, c: number, d: number) => void;
export const reactionlenssimulation_advance_dark_steps: (a: number, b: number, c: number, d: number) => void;
export const reactionlenssimulation_advance_development_steps: (a: number, b: number) => number;
export const reactionlenssimulation_get_snapshot: (a: number) => number;
export const reactionlenssimulation_snapshot_len: (a: number) => number;
export const reactionlenssimulation_get_diagnostics: (a: number, b: number) => void;
export const create_simulation: (a: number, b: number, c: number) => void;
export const __wbg_wholevolumesimulation_free: (a: number, b: number) => void;
export const wholevolumesimulation_new: (a: number, b: number, c: number, d: number) => void;
export const wholevolumesimulation_set_parameters: (a: number, b: number, c: number) => void;
export const wholevolumesimulation_reset: (a: number) => void;
export const wholevolumesimulation_advance_exposure_steps: (a: number, b: number) => number;
export const wholevolumesimulation_advance_development_steps: (a: number, b: number) => number;
export const wholevolumesimulation_get_snapshot: (a: number) => number;
export const wholevolumesimulation_snapshot_len: (a: number) => number;
export const wholevolumesimulation_focus: (a: number, b: number) => void;
export const wholevolumesimulation_exposure_progress: (a: number) => number;
export const wholevolumesimulation_development_progress: (a: number) => number;
export const wholevolumesimulation_get_diagnostics: (a: number, b: number) => void;
export const reactionlenssimulation_new: (a: number, b: number, c: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number) => void;
